version: '3.4'

services:
  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Order@123
    restart: always
    ports:
      - "1433:1433"

  orderservice.api:
    image: orderserviceapi
    build:
      context: .
      dockerfile: src/OrderService.Api/Dockerfile
    depends_on:
      - orderdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
