<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Basket.CheckOutEvent" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OrderService.Contracts\OrderService.Contracts.csproj" />
    <ProjectReference Include="..\..\src\OrderService.Domain\OrderService.Domain.csproj" />
  </ItemGroup>

</Project>
