global using OrderService.Domain.Entities;
global using OrderService.Domain.ValueObjects;
global using OrderService.Infrastructure.Data.Seeding;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using OrderService.Domain.Common;
global using OrderService.Infrastructure.Data.Extensions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
